
package com.tracfone.b2b.inquiryservices.balanceinquiry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "BalanceInquiryService", targetNamespace = "http://b2b.tracfone.com/InquiryServices/BalanceInquiry", wsdlLocation = "file:/F:/TracfoneAD/src/com/jacada/tracfoneAD/webServices/wsdl/BalanceInquiry.wsdl")
public class BalanceInquiryService_Service
    extends Service
{

    private final static URL BALANCEINQUIRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException BALANCEINQUIRYSERVICE_EXCEPTION;
    private final static QName BALANCEINQUIRYSERVICE_QNAME = new QName("http://b2b.tracfone.com/InquiryServices/BalanceInquiry", "BalanceInquiryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/TracfoneAD/src/com/jacada/tracfoneAD/webServices/wsdl/BalanceInquiry.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BALANCEINQUIRYSERVICE_WSDL_LOCATION = url;
        BALANCEINQUIRYSERVICE_EXCEPTION = e;
    }

    public BalanceInquiryService_Service() {
        super(__getWsdlLocation(), BALANCEINQUIRYSERVICE_QNAME);
    }

    public BalanceInquiryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns BalanceInquiryService
     */
    @WebEndpoint(name = "BalanceInquiryService")
    public BalanceInquiryService getBalanceInquiryService() {
        return super.getPort(new QName("http://b2b.tracfone.com/InquiryServices/BalanceInquiry", "BalanceInquiryService"), BalanceInquiryService.class);
    }

    private static URL __getWsdlLocation() {
        if (BALANCEINQUIRYSERVICE_EXCEPTION!= null) {
            throw BALANCEINQUIRYSERVICE_EXCEPTION;
        }
        return BALANCEINQUIRYSERVICE_WSDL_LOCATION;
    }

}
